model:
    target: enhancing.modules.stage1.vitvqgan.ViTVQGumbel
    params:
        image_key: image
        temperature_scheduler:
            target: enhancing.utils.callback.LambdaWarmUpCosineScheduler
            params:
                warm_up_steps: 1000
                min_: 0.16
                max_: 1
                start: 0.9
                max_decay_steps: 100000
        hparams:
            image_size: 256
            patch_size: 16
            dim: 768
            depth: 12
            heads: 12
            mlp_dim: 3072
        qparams:
            embed_dim: 256
            n_embed: 16384
            use_residual: True
            num_quantizers: 4
        loss:
            target: enhancing.losses.vqperceptual.VQLPIPSWithDiscriminator
            params:
                disc_start: 250001
                loglaplace_weight: 0.1
                loggaussian_weight: 1.0
                perceptual_weight: 0.1

dataset:
    target: enhancing.dataloader.DataModuleFromConfig
    params:
        batch_size: 4
        num_workers: 2
        train:
            target: enhancing.dataloader.lsun.LSUNTrain
            params:
                root: data
                classes: church_outdoor
                resolution: 256
                
        validation:
            target: enhancing.dataloader.lsun.LSUNValidation
            params:
                root: data
                classes: church_outdoor
                resolution: 256
