model:
    target: enhancing.modules.stage2.transformer.CondTransformer
    params:
        cond_key: class
        cond: 
            target: enhancing.modules.cond.dummycond.ClassCond
            params:
                image_size: 256
                class_name: ["church_outdoor"]
        stage1:
            target: enhancing.modules.stage1.vitvqgan.ViTVQGumbel
            params:
                image_key: image
                temperature_scheduler:
                    target: enhancing.utils.callback.DummyScheduler
                hparams:
                    image_size: 256
                    patch_size: 32
                    dim: 768
                    depth: 12
                    heads: 12
                    mlp_dim: 2048
                qparams:
                    embed_dim: 256
                    n_embed: 16384
                    use_residual: True
                    num_quantizers: 4
                loss:
                    target: enhancing.losses.vqperceptual.DummyLoss
        transformer:
            target: enhancing.modules.stage2.layers.RQTransformer
            params:
                vocab_cond_size: 1
                vocab_img_size: 16384
                embed_dim: 6144
                cond_num_tokens: 1
                img_num_tokens: 8 
                depth_num_tokens: 4 
                spatial_n_heads: 16
                spatial_n_layers: 24
                depth_n_heads: 16
                depth_n_layers: 4

dataset:
    target: enhancing.dataloader.DataModuleFromConfig
    params:
        batch_size: 4
        num_workers: 2
        train:
            target: enhancing.dataloader.lsun.LSUNTrain
            params:
                root: data
                classes: church_outdoor
                resolution: 256
                
        validation:
            target: enhancing.dataloader.lsun.LSUNValidation
            params:
                root: data
                classes: church_outdoor
                resolution: 256
