model:
    target: enhancing.modules.stage1.vqsae.VQGumbel
    params:
        image_key: image
        temperature_scheduler:
            target: enhancing.utils.scheduler.LambdaWarmUpCosineScheduler
            params:
                warm_up_steps: 1000
                min_: 0.16
                max_: 1
                start: 0.9
                max_decay_steps: 100000
        hparams:
            dims: [3, 192, 384, 384, 384]
            hidden_dims: [48, 96, 96, 96]
            stage_depths: [4, 3, 8, 3]
            scales: [7, 2, 1, 1]
            mlp_ratio: 3
        qparams:
            embed_dim: 32 
            n_embed: 8192 
            use_residual: True
            num_quantizers: 4
        loss:
            target: enhancing.losses.vqperceptual.VQLPIPSWithDiscriminator
            params:
                disc_start: 50001
                loglaplace_weight: 0.1
                loggaussian_weight: 1.0
                perceptual_weight: 0.1
                codebook_weight: 1.0

dataset:
    target: enhancing.dataloader.DataModuleFromConfig
    params:
        batch_size: 4
        num_workers: 2
        train:
            target: enhancing.dataloader.classimage.ClassImageTrain
            params:
                root: data
                resolution: 224
                
        validation:
            target: enhancing.dataloader.classimage.ClassImageValidation
            params:
                root: data
                resolution: 224